version: '3'
services:
  iadvizescalatest:
    build: .
    ports:
    - "8080:8080"
    working_dir: /app
    stdin_open: true
    command: bash -c "sbt \";runMain com.iadvize.vdm.scrapper.VDMSiteScrapper; jetty:start; console\""