version: '3'
services:
  iadvizescalatest:
    build: .
    ports:
    - "8080:8080"
    working_dir: /app
    command: bash -c "java -cp target/scala-2.12/IadvizeScalaTest-assembly-0.1.0-SNAPSHOT.jar com.iadvize.vdm.scrapper.VDMSiteScrapper;java -cp target/scala-2.12/IadvizeScalaTest-assembly-0.1.0-SNAPSHOT.jar JettyLauncher"